### PR TITLE
Store L3 temporary files in temporary directory

### LINKED ISSUE #4: Parallelizing "fit()" does not work.
Given an instance of L3Classifier, the parallelization of the fitting (e.g. via `GridSearchCV` or `joblib.Parallel` is not working due to the inner functioning of L3. Its binaries create intermediate result files during for example DBCoverage and more. These are not labeled with a stem or token, hence they come in contrast if multiple runs of the same executable are active in the same working directory.
 
The problem might be overcome by creating a new folder on the fly (yet, I know, another IO operation), moving into it and perform training.

### PR DESCRIPTION
**Pull request by mrandri19**
Currently L3's temporary files are stored (temporarily if `remove_file=True`) in the folder from where python is launched. This means that if two or more instances of the classifier are run in parallel, files such as `livelloI.txt` will get overwritten.

With this change, each time `fit` is called, a unique temporary folder is created to store the temporary files, which gets deleted at the end of the method. In this way I can run many (I've tried up to 8) classifications in parallel with `multiprocessing.Pool` for example.

The only problem I can see is
```python
self.current_token_ = token # keep track of the latest token generated by the fit method
```
which now stores the path of a directory which has been removed. But this attribute is not used anywhere in the library so it causes no issues.

### CODE REVIEW

**Comment by g8a9** [comment]
Hey @mrandri19, sorry for getting you back this late. I have gone through your changes and I can see the problem you address (I did link the issue on parallel training to this PR, long long time ago).

However, I would propose you to change them a bit. Specifically, I would keep the definition of the **current_token** as a unique identifier, while in your code is now a _path_. Indeed, the *_remove_fit_file* method would empty the directory leaving it as it is. 

Perhaps, to keep the logic unchanged, we can:
- create a temporary directory as you already do
- move into it as cwd
- carry out all the training-related stuff
- get back to the original working directory.

What do you think?

**Comment by mrandri19** [comment]
Yeah, that could work, I can close this and open a new PR if you want
(by the way I have just discovered that clicking the gear icon while in the Files changed view lets you hide white-space changes and makes the diff much more readable)

**Comment by g8a9** [comment]
For simplicity, we could stick with this PR. If you have time, just push as many commits as you need here. 

P.S. Thanks for the hint on white spaces, not sure it was there before. But it's waaaaaay better.

**Comment by mrandri19** [comment]
I have had some issues while trying to rebase the new commit onto my fork so I have created [a new PR](https://github.com/g8a9/l3wrapper/pull/8)

**Pull request closed without merging**
